### ISSUE TITLE
either get rid of the backdrop photo, or move the twitter feed to be on top of the photo on one of the sides

### ISSUE THREAD

**Issue by darinpierson** [snowy-pier-games/spgbackend#11]

**Comment by kyledpierson** [comment]
I saw other bg publisher websites do a backdrop image to narrow their content to the center of the screen, and I kinda liked it.

https://stonemaiergames.com/

Although, that just might be because the screen that I develop on is really big, and having the content span the whole screen looked like too much. I’m open to change.

**Comment by darinpierson** [comment]
Yeah i am fine either way. I'd probably lean not having the backdrop. It looks more modern without it. However, if we keep the backdrop, i'd kill the social media feed. It feels like there isn't enough space with the backdrop. What do you guys want to do?
